# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Copyright (c) 2023 Nelson Vieira
#
# @author Nelson Vieira <2080511@student.uma.pt>
# @license AGPL-3.0 <https://www.gnu.org/licenses/agpl-3.0.txt>
arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
